### ISSUE TITLE
Round 1

### ISSUE THREAD

**Issue by arsangeta** [karansinghtomar123/SMS-Lucknow#2]
Focus area incorrect
Cognitive level contradiction
Instructional Strategy incorrect
Assessment questions do not have answers
In simulator you are not asking option to convert which base.
Simulator actions need to be revised

Wrong spelling Decimal in step 2 of simulator

**Comment by hemantbib** [comment]
ok mam than we  will try to correct it

**Comment by hemantbib** [comment]
OK mam thanks, we will try to correct it.
